spring:
  application:
    name: orders-service
  datasource:
    url: ${ORDERS_DB_URL:jdbc:mysql://${ORDERS_DB_HOST:localhost}:${ORDERS_DB_PORT:3306}/${ORDERS_DB_NAME:orders_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${ORDERS_DB_USERNAME:orders}
    password: ${ORDERS_DB_PASSWORD:orders}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    time-zone: UTC

server:
  port: ${SERVER_PORT:8083}
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,db
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  auth:
    users-service-base-url: ${USERS_SERVICE_BASE_URL:http://localhost:8081}
    users-service-token: ${ORDERS_TO_USERS_SERVICE_TOKEN:local-dev-token}
    application-name: ${APP_AUTH_NAME:orders-service}
    application-secret: ${APP_AUTH_SECRET:orders-service-secret}
    token-refresh-factor: ${APP_AUTH_REFRESH_FACTOR:0.8}
  menu:
    base-url: ${MENU_SERVICE_BASE_URL:http://localhost:8082}
