spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/menu_db

management:
  endpoint:
    health:
      show-details: always

app:
  auth:
    users-service-base-url: http://localhost:8081
    users-service-token: local-dev-token
