spring:
  application:
    name: menu-service
  data:
    mongodb:
      uri: ${MENU_DB_URI:mongodb://${MENU_DB_HOST:localhost}:${MENU_DB_PORT:27017}/${MENU_DB_NAME:menu_db}}

server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,mongo
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  runtime:
    required-java-feature: ${JAVA_FEATURE_REQUIRED:21}
  security:
    internal-service-token: ${MENU_INTERNAL_SERVICE_TOKEN:menu-internal-token}
  auth:
    users-service-base-url: ${USERS_SERVICE_BASE_URL:http://localhost:8081}
    users-service-token: ${MENU_TO_USERS_SERVICE_TOKEN:local-dev-token}
    application-name: ${APP_AUTH_NAME:menu-service}
    application-secret: ${APP_AUTH_SECRET:menu-service-secret}
    token-refresh-factor: ${APP_AUTH_REFRESH_FACTOR:0.8}
